"""Add telegram fields to BusinessConfig

Revision ID: 73fc71d87115
Revises: 
Create Date: 2026-02-11 01:20:31.708651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73fc71d87115'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_bot_token', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')
        batch_op.drop_column('telegram_bot_token')

    # ### end Alembic commands ###
