"""Add JSON config fields to BusinessConfig

Revision ID: c054d0ecc10f
Revises: f87938667fe8
Create Date: 2026-02-11 16:52:02.552242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c054d0ecc10f'
down_revision = 'f87938667fe8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('styling_config', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('email_config', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.drop_column('email_config')
        batch_op.drop_column('styling_config')
        batch_op.drop_column('appointment_config')

    # ### end Alembic commands ###
