"""add appointment toggle and hours fields

Revision ID: f87938667fe8
Revises: 73fc71d87115
Create Date: 2026-02-11 11:39:32.015423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f87938667fe8'
down_revision = '73fc71d87115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('appointment_hours', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('appointment_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('business_config', schema=None) as batch_op:
        batch_op.drop_column('appointment_notes')
        batch_op.drop_column('appointment_hours')
        batch_op.drop_column('appointment_enabled')

    # ### end Alembic commands ###
